export const PRODUCT_TYPES = [
    'блюдо',
    'блюдце',
    'кофейный сервиз',
    'кружка',
    'кувшин',
    'лоток',
    'маслёнка',
    'миска',
    'набор',
    'пиала',
    'предмет',
    'прибор для специй',
    'салатник',
    'сахарница',
    'селедочница',
    'стакан',
    'столовый сервиз',
    'сувенир',
    'тарелка',
    'чайная пара',
    'чайный сервиз',
    'чашка',
    'этажерка',
] as const;

export const PRODUCT_TYPE_LABEL_KEYS: Record<(typeof PRODUCT_TYPES)[number], string> = {
    'блюдо': 'product.type_dish',
    'блюдце': 'product.type_saucer',
    'кофейный сервиз': 'product.type_coffee_service',
    'кружка': 'product.type_mug',
    'кувшин': 'product.type_pitcher',
    'лоток': 'product.type_tray',
    'маслёнка': 'product.type_butter_dish',
    'миска': 'product.type_bowl',
    'набор': 'product.type_set',
    'пиала': 'product.type_piala',
    'предмет': 'product.type_item',
    'прибор для специй': 'product.type_spice_set',
    'салатник': 'product.type_salad_bowl',
    'сахарница': 'product.type_sugar_bowl',
    'селедочница': 'product.type_herring_dish',
    'стакан': 'product.type_glass',
    'столовый сервиз': 'product.type_dinner_service',
    'сувенир': 'product.type_souvenir',
    'тарелка': 'product.type_plate',
    'чайная пара': 'product.type_tea_pair',
    'чайный сервиз': 'product.type_tea_service',
    'чашка': 'product.type_cup',
    'этажерка': 'product.type_tiered_stand',
};